// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: emailService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnapchatLibProto.Snapchat.Activation.Api {

  /// <summary>Holder for reflection information generated from emailService.proto</summary>
  public static partial class EmailServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for emailService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EmailServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJlbWFpbFNlcnZpY2UucHJvdG8SF3NuYXBjaGF0LmFjdGl2YXRpb24uYXBp",
            "IssCChJVcGRhdGVFbWFpbFJlcXVlc3QSFgoOcmVxdWVzdGVkRW1haWwYASAB",
            "KAkSbAoGYWN0aW9uGAIgASgOMlwuc25hcGNoYXQuYWN0aXZhdGlvbi5hcGku",
            "VXBkYXRlRW1haWxSZXF1ZXN0LlNDQWNjb3VudEVtYWlsU2VydmljZVBiVXBk",
            "YXRlRW1haWxSZXF1ZXN0X0FjdGlvbhIYChBibGl6emFyZENsaWVudElkGAMg",
            "ASgJEhcKD2FuZHJvaWRJZEFzTG9uZxgEIAEoCRIMCgR1dWlkGAUgASgJIm4K",
            "MFNDQWNjb3VudEVtYWlsU2VydmljZVBiVXBkYXRlRW1haWxSZXF1ZXN0X0Fj",
            "dGlvbhIJCgVVTlNFVBAAEhAKDENIQU5HRV9FTUFJTBABEh0KGVJFU0VORF9D",
            "T05GSVJNQVRJT05fRU1BSUwQAiJnChNVcGRhdGVFbWFpbFJlc3BvbnNlEhAK",
            "CGlzX2FsbG93GAEgASgIEj4KDnN0cmluZ19tZXNzYWdlGAIgASgLMiYuc25h",
            "cGNoYXQuYWN0aXZhdGlvbi5hcGkuU3RyaW5nTWVzc2FnZSIgCg1TdHJpbmdN",
            "ZXNzYWdlEg8KB21lc3NhZ2UYASABKAkygQEKE0FjY291bnRFbWFpbFNlcnZp",
            "Y2USagoLVXBkYXRlRW1haWwSKy5zbmFwY2hhdC5hY3RpdmF0aW9uLmFwaS5V",
            "cGRhdGVFbWFpbFJlcXVlc3QaLC5zbmFwY2hhdC5hY3RpdmF0aW9uLmFwaS5V",
            "cGRhdGVFbWFpbFJlc3BvbnNlIgBCLUgDqgIoU25hcGNoYXRMaWJQcm90by5T",
            "bmFwY2hhdC5BY3RpdmF0aW9uLkFwaWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest), global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Parser, new[]{ "RequestedEmail", "Action", "BlizzardClientId", "AndroidIdAsLong", "Uuid" }, null, new[]{ typeof(global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailResponse), global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailResponse.Parser, new[]{ "IsAllow", "StringMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage), global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage.Parser, new[]{ "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UpdateEmailRequest : pb::IMessage<UpdateEmailRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateEmailRequest> _parser = new pb::MessageParser<UpdateEmailRequest>(() => new UpdateEmailRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateEmailRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.EmailServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailRequest(UpdateEmailRequest other) : this() {
      requestedEmail_ = other.requestedEmail_;
      action_ = other.action_;
      blizzardClientId_ = other.blizzardClientId_;
      androidIdAsLong_ = other.androidIdAsLong_;
      uuid_ = other.uuid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailRequest Clone() {
      return new UpdateEmailRequest(this);
    }

    /// <summary>Field number for the "requestedEmail" field.</summary>
    public const int RequestedEmailFieldNumber = 1;
    private string requestedEmail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestedEmail {
      get { return requestedEmail_; }
      set {
        requestedEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action action_ = global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "blizzardClientId" field.</summary>
    public const int BlizzardClientIdFieldNumber = 3;
    private string blizzardClientId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BlizzardClientId {
      get { return blizzardClientId_; }
      set {
        blizzardClientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "androidIdAsLong" field.</summary>
    public const int AndroidIdAsLongFieldNumber = 4;
    private string androidIdAsLong_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AndroidIdAsLong {
      get { return androidIdAsLong_; }
      set {
        androidIdAsLong_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 5;
    private string uuid_ = "";
    /// <summary>
    /// random uuid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateEmailRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateEmailRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestedEmail != other.RequestedEmail) return false;
      if (Action != other.Action) return false;
      if (BlizzardClientId != other.BlizzardClientId) return false;
      if (AndroidIdAsLong != other.AndroidIdAsLong) return false;
      if (Uuid != other.Uuid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestedEmail.Length != 0) hash ^= RequestedEmail.GetHashCode();
      if (Action != global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset) hash ^= Action.GetHashCode();
      if (BlizzardClientId.Length != 0) hash ^= BlizzardClientId.GetHashCode();
      if (AndroidIdAsLong.Length != 0) hash ^= AndroidIdAsLong.GetHashCode();
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestedEmail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestedEmail);
      }
      if (Action != global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Action);
      }
      if (BlizzardClientId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BlizzardClientId);
      }
      if (AndroidIdAsLong.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AndroidIdAsLong);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestedEmail.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestedEmail);
      }
      if (Action != global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Action);
      }
      if (BlizzardClientId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BlizzardClientId);
      }
      if (AndroidIdAsLong.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AndroidIdAsLong);
      }
      if (Uuid.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Uuid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestedEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestedEmail);
      }
      if (Action != global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (BlizzardClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BlizzardClientId);
      }
      if (AndroidIdAsLong.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AndroidIdAsLong);
      }
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateEmailRequest other) {
      if (other == null) {
        return;
      }
      if (other.RequestedEmail.Length != 0) {
        RequestedEmail = other.RequestedEmail;
      }
      if (other.Action != global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action.Unset) {
        Action = other.Action;
      }
      if (other.BlizzardClientId.Length != 0) {
        BlizzardClientId = other.BlizzardClientId;
      }
      if (other.AndroidIdAsLong.Length != 0) {
        AndroidIdAsLong = other.AndroidIdAsLong;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestedEmail = input.ReadString();
            break;
          }
          case 16: {
            Action = (global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action) input.ReadEnum();
            break;
          }
          case 26: {
            BlizzardClientId = input.ReadString();
            break;
          }
          case 34: {
            AndroidIdAsLong = input.ReadString();
            break;
          }
          case 42: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RequestedEmail = input.ReadString();
            break;
          }
          case 16: {
            Action = (global::SnapchatLibProto.Snapchat.Activation.Api.UpdateEmailRequest.Types.SCAccountEmailServicePbUpdateEmailRequest_Action) input.ReadEnum();
            break;
          }
          case 26: {
            BlizzardClientId = input.ReadString();
            break;
          }
          case 34: {
            AndroidIdAsLong = input.ReadString();
            break;
          }
          case 42: {
            Uuid = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the UpdateEmailRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum SCAccountEmailServicePbUpdateEmailRequest_Action {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("CHANGE_EMAIL")] ChangeEmail = 1,
        [pbr::OriginalName("RESEND_CONFIRMATION_EMAIL")] ResendConfirmationEmail = 2,
      }

    }
    #endregion

  }

  public sealed partial class UpdateEmailResponse : pb::IMessage<UpdateEmailResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateEmailResponse> _parser = new pb::MessageParser<UpdateEmailResponse>(() => new UpdateEmailResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateEmailResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.EmailServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailResponse(UpdateEmailResponse other) : this() {
      isAllow_ = other.isAllow_;
      stringMessage_ = other.stringMessage_ != null ? other.stringMessage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEmailResponse Clone() {
      return new UpdateEmailResponse(this);
    }

    /// <summary>Field number for the "is_allow" field.</summary>
    public const int IsAllowFieldNumber = 1;
    private bool isAllow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAllow {
      get { return isAllow_; }
      set {
        isAllow_ = value;
      }
    }

    /// <summary>Field number for the "string_message" field.</summary>
    public const int StringMessageFieldNumber = 2;
    private global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage stringMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage StringMessage {
      get { return stringMessage_; }
      set {
        stringMessage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateEmailResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateEmailResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsAllow != other.IsAllow) return false;
      if (!object.Equals(StringMessage, other.StringMessage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsAllow != false) hash ^= IsAllow.GetHashCode();
      if (stringMessage_ != null) hash ^= StringMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IsAllow != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAllow);
      }
      if (stringMessage_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StringMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IsAllow != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsAllow);
      }
      if (stringMessage_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StringMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsAllow != false) {
        size += 1 + 1;
      }
      if (stringMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StringMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateEmailResponse other) {
      if (other == null) {
        return;
      }
      if (other.IsAllow != false) {
        IsAllow = other.IsAllow;
      }
      if (other.stringMessage_ != null) {
        if (stringMessage_ == null) {
          StringMessage = new global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage();
        }
        StringMessage.MergeFrom(other.StringMessage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsAllow = input.ReadBool();
            break;
          }
          case 18: {
            if (stringMessage_ == null) {
              StringMessage = new global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage();
            }
            input.ReadMessage(StringMessage);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            IsAllow = input.ReadBool();
            break;
          }
          case 18: {
            if (stringMessage_ == null) {
              StringMessage = new global::SnapchatLibProto.Snapchat.Activation.Api.StringMessage();
            }
            input.ReadMessage(StringMessage);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StringMessage : pb::IMessage<StringMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StringMessage> _parser = new pb::MessageParser<StringMessage>(() => new StringMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StringMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.EmailServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StringMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StringMessage(StringMessage other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StringMessage Clone() {
      return new StringMessage(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StringMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StringMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StringMessage other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
