// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: JanusService.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SnapchatLibProto.Snapchat.Janus.Api {
  public static partial class RegistrationService
  {
    static readonly string __ServiceName = "snapchat.janus.api.RegistrationService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest> __Marshaller_snapchat_janus_api_SCJanusRegisterWithUsernamePasswordRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse> __Marshaller_snapchat_janus_api_SCJanusRegisterWithUsernamePasswordResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse> __Method_RegisterWithUsernamePassword = new grpc::Method<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RegisterWithUsernamePassword",
        __Marshaller_snapchat_janus_api_SCJanusRegisterWithUsernamePasswordRequest,
        __Marshaller_snapchat_janus_api_SCJanusRegisterWithUsernamePasswordResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SnapchatLibProto.Snapchat.Janus.Api.JanusServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RegistrationService</summary>
    [grpc::BindServiceMethod(typeof(RegistrationService), "BindService")]
    public abstract partial class RegistrationServiceBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse> RegisterWithUsernamePassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RegistrationService</summary>
    public partial class RegistrationServiceClient : grpc::ClientBase<RegistrationServiceClient>
    {
      /// <summary>Creates a new client for RegistrationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RegistrationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RegistrationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RegistrationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RegistrationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RegistrationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse RegisterWithUsernamePassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterWithUsernamePassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse RegisterWithUsernamePassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RegisterWithUsernamePassword, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse> RegisterWithUsernamePasswordAsync(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterWithUsernamePasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse> RegisterWithUsernamePasswordAsync(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RegisterWithUsernamePassword, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RegistrationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RegistrationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RegistrationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RegisterWithUsernamePassword, serviceImpl.RegisterWithUsernamePassword).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RegistrationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RegisterWithUsernamePassword, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusRegisterWithUsernamePasswordResponse>(serviceImpl.RegisterWithUsernamePassword));
    }

  }
  public static partial class LoginService
  {
    static readonly string __ServiceName = "snapchat.janus.api.LoginService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest> __Marshaller_snapchat_janus_api_SCJanusLoginWithPasswordRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse> __Marshaller_snapchat_janus_api_SCJanusLoginWithPasswordResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse> __Method_LoginWithPassword = new grpc::Method<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoginWithPassword",
        __Marshaller_snapchat_janus_api_SCJanusLoginWithPasswordRequest,
        __Marshaller_snapchat_janus_api_SCJanusLoginWithPasswordResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SnapchatLibProto.Snapchat.Janus.Api.JanusServiceReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of LoginService</summary>
    [grpc::BindServiceMethod(typeof(LoginService), "BindService")]
    public abstract partial class LoginServiceBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse> LoginWithPassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LoginService</summary>
    public partial class LoginServiceClient : grpc::ClientBase<LoginServiceClient>
    {
      /// <summary>Creates a new client for LoginService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LoginServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LoginService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LoginServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LoginServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LoginServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse LoginWithPassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginWithPassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse LoginWithPassword(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoginWithPassword, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse> LoginWithPasswordAsync(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginWithPasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse> LoginWithPasswordAsync(global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoginWithPassword, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LoginServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LoginServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LoginServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_LoginWithPassword, serviceImpl.LoginWithPassword).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LoginServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_LoginWithPassword, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordRequest, global::SnapchatLibProto.Snapchat.Janus.Api.SCJanusLoginWithPasswordResponse>(serviceImpl.LoginWithPassword));
    }

  }
}
#endregion
