// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SuggestUsernameService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SnapchatLibProto.Snapchat.Activation.Api {

  /// <summary>Holder for reflection information generated from SuggestUsernameService.proto</summary>
  public static partial class SuggestUsernameServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for SuggestUsernameService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SuggestUsernameServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxTdWdnZXN0VXNlcm5hbWVTZXJ2aWNlLnByb3RvEhdzbmFwY2hhdC5hY3Rp",
            "dmF0aW9uLmFwaSKSAgorU0NTdWdnZXN0VXNlcm5hbWVQYlN1Z2dlc3RVc2Vy",
            "bmFtZVJlcXVlc3RWMhJvChBuYW1lQW5kQmlydGhkYXRlGAEgASgLMlUuc25h",
            "cGNoYXQuYWN0aXZhdGlvbi5hcGkuU0NTdWdnZXN0VXNlcm5hbWVQYlN1Z2dl",
            "c3RVc2VybmFtZVJlcXVlc3RWMi5OYW1lQW5kQmlydGhkYXRlEhUKDXZlcnNp",
            "b25OdW1iZXIYAiABKA0SEAoIZGV2aWNlSWQYAyABKAkSEAoIY2xpZW50SWQY",
            "BCABKAkaNwoQTmFtZUFuZEJpcnRoZGF0ZRIRCglmaXJzdE5hbWUYASABKAkS",
            "EAoIbGFzdE5hbWUYAiABKAkiXwosU0NTdWdnZXN0VXNlcm5hbWVQYlN1Z2dl",
            "c3RVc2VybmFtZVJlc3BvbnNlVjISGAoQc3VnZ2VzdGlvbnNBcnJheRgBIAMo",
            "CRIVCg12ZXJzaW9uTnVtYmVyGAIgASgNIoEBCilTQ1N1Z2dlc3RVc2VybmFt",
            "ZVBiQ2hlY2tVc2VybmFtZVJlcXVlc3RWMhIZChFyZXF1ZXN0ZWRVc2VybmFt",
            "ZRgBIAEoCRIVCg12ZXJzaW9uTnVtYmVyGAMgASgNEhAKCGRldmljZUlkGAQg",
            "ASgJEhAKCGNsaWVudElkGAUgASgJIv0ICipTQ1N1Z2dlc3RVc2VybmFtZVBi",
            "Q2hlY2tVc2VybmFtZVJlc3BvbnNlVjISkwEKBXN0YXRlGAEgASgOMoMBLnNu",
            "YXBjaGF0LmFjdGl2YXRpb24uYXBpLlNDU3VnZ2VzdFVzZXJuYW1lUGJDaGVj",
            "a1VzZXJuYW1lUmVzcG9uc2VWMi5TQ1N1Z2dlc3RVc2VybmFtZVBiQ2hlY2tV",
            "c2VybmFtZVJlc3BvbnNlX1JlcXVlc3RlZFVzZXJuYW1lU3RhdGUiuAcKP1ND",
            "U3VnZ2VzdFVzZXJuYW1lUGJDaGVja1VzZXJuYW1lUmVzcG9uc2VfUmVxdWVz",
            "dGVkVXNlcm5hbWVTdGF0ZRJOCkpTQ1N1Z2dlc3RVc2VybmFtZVBiQ2hlY2tV",
            "c2VybmFtZVJlc3BvbnNlX1JlcXVlc3RlZFVzZXJuYW1lU3RhdGVfU3RhdGVV",
            "bnNldBAAElUKUVNDU3VnZ2VzdFVzZXJuYW1lUGJDaGVja1VzZXJuYW1lUmVz",
            "cG9uc2VfUmVxdWVzdGVkVXNlcm5hbWVTdGF0ZV9Vc2VybmFtZUF2YWlsYWJs",
            "ZRABEkwKSFNDU3VnZ2VzdFVzZXJuYW1lUGJDaGVja1VzZXJuYW1lUmVzcG9u",
            "c2VfUmVxdWVzdGVkVXNlcm5hbWVTdGF0ZV9Ub29TaG9ydBACEksKR1NDU3Vn",
            "Z2VzdFVzZXJuYW1lUGJDaGVja1VzZXJuYW1lUmVzcG9uc2VfUmVxdWVzdGVk",
            "VXNlcm5hbWVTdGF0ZV9Ub29Mb25nEAMSUApMU0NTdWdnZXN0VXNlcm5hbWVQ",
            "YkNoZWNrVXNlcm5hbWVSZXNwb25zZV9SZXF1ZXN0ZWRVc2VybmFtZVN0YXRl",
            "X0ludmFsaWRCZWdpbhAEEk4KSlNDU3VnZ2VzdFVzZXJuYW1lUGJDaGVja1Vz",
            "ZXJuYW1lUmVzcG9uc2VfUmVxdWVzdGVkVXNlcm5hbWVTdGF0ZV9JbnZhbGlk",
            "RW5kEAUSTwpLU0NTdWdnZXN0VXNlcm5hbWVQYkNoZWNrVXNlcm5hbWVSZXNw",
            "b25zZV9SZXF1ZXN0ZWRVc2VybmFtZVN0YXRlX0ludmFsaWRDaGFyEAYSVApQ",
            "U0NTdWdnZXN0VXNlcm5hbWVQYkNoZWNrVXNlcm5hbWVSZXNwb25zZV9SZXF1",
            "ZXN0ZWRVc2VybmFtZVN0YXRlX0ludmFsaWRTZXBhcmF0ZWQQBxJJCkVTQ1N1",
            "Z2dlc3RVc2VybmFtZVBiQ2hlY2tVc2VybmFtZVJlc3BvbnNlX1JlcXVlc3Rl",
            "ZFVzZXJuYW1lU3RhdGVfVGFrZW4QCBJLCkdTQ1N1Z2dlc3RVc2VybmFtZVBi",
            "Q2hlY2tVc2VybmFtZVJlc3BvbnNlX1JlcXVlc3RlZFVzZXJuYW1lU3RhdGVf",
            "RGVsZXRlZBAJElIKTlNDU3VnZ2VzdFVzZXJuYW1lUGJDaGVja1VzZXJuYW1l",
            "UmVzcG9uc2VfUmVxdWVzdGVkVXNlcm5hbWVTdGF0ZV9TYW1lQXNQYXNzd29y",
            "ZBAKMtQCChZTdWdnZXN0VXNlcm5hbWVTZXJ2aWNlEp4BCg9TdWdnZXN0VXNl",
            "cm5hbWUSRC5zbmFwY2hhdC5hY3RpdmF0aW9uLmFwaS5TQ1N1Z2dlc3RVc2Vy",
            "bmFtZVBiU3VnZ2VzdFVzZXJuYW1lUmVxdWVzdFYyGkUuc25hcGNoYXQuYWN0",
            "aXZhdGlvbi5hcGkuU0NTdWdnZXN0VXNlcm5hbWVQYlN1Z2dlc3RVc2VybmFt",
            "ZVJlc3BvbnNlVjISmAEKDUNoZWNrVXNlcm5hbWUSQi5zbmFwY2hhdC5hY3Rp",
            "dmF0aW9uLmFwaS5TQ1N1Z2dlc3RVc2VybmFtZVBiQ2hlY2tVc2VybmFtZVJl",
            "cXVlc3RWMhpDLnNuYXBjaGF0LmFjdGl2YXRpb24uYXBpLlNDU3VnZ2VzdFVz",
            "ZXJuYW1lUGJDaGVja1VzZXJuYW1lUmVzcG9uc2VWMkIrqgIoU25hcGNoYXRM",
            "aWJQcm90by5TbmFwY2hhdC5BY3RpdmF0aW9uLkFwaWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2), global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Parser, new[]{ "NameAndBirthdate", "VersionNumber", "DeviceId", "ClientId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate), global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate.Parser, new[]{ "FirstName", "LastName" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameResponseV2), global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameResponseV2.Parser, new[]{ "SuggestionsArray", "VersionNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameRequestV2), global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameRequestV2.Parser, new[]{ "RequestedUsername", "VersionNumber", "DeviceId", "ClientId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2), global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Parser, new[]{ "State" }, null, new[]{ typeof(global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Define the request message for username suggestion
  /// </summary>
  public sealed partial class SCSuggestUsernamePbSuggestUsernameRequestV2 : pb::IMessage<SCSuggestUsernamePbSuggestUsernameRequestV2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SCSuggestUsernamePbSuggestUsernameRequestV2> _parser = new pb::MessageParser<SCSuggestUsernamePbSuggestUsernameRequestV2>(() => new SCSuggestUsernamePbSuggestUsernameRequestV2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SCSuggestUsernamePbSuggestUsernameRequestV2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.SuggestUsernameServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameRequestV2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameRequestV2(SCSuggestUsernamePbSuggestUsernameRequestV2 other) : this() {
      nameAndBirthdate_ = other.nameAndBirthdate_ != null ? other.nameAndBirthdate_.Clone() : null;
      versionNumber_ = other.versionNumber_;
      deviceId_ = other.deviceId_;
      clientId_ = other.clientId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameRequestV2 Clone() {
      return new SCSuggestUsernamePbSuggestUsernameRequestV2(this);
    }

    /// <summary>Field number for the "nameAndBirthdate" field.</summary>
    public const int NameAndBirthdateFieldNumber = 1;
    private global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate nameAndBirthdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate NameAndBirthdate {
      get { return nameAndBirthdate_; }
      set {
        nameAndBirthdate_ = value;
      }
    }

    /// <summary>Field number for the "versionNumber" field.</summary>
    public const int VersionNumberFieldNumber = 2;
    private uint versionNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint VersionNumber {
      get { return versionNumber_; }
      set {
        versionNumber_ = value;
      }
    }

    /// <summary>Field number for the "deviceId" field.</summary>
    public const int DeviceIdFieldNumber = 3;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 4;
    private string clientId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SCSuggestUsernamePbSuggestUsernameRequestV2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SCSuggestUsernamePbSuggestUsernameRequestV2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NameAndBirthdate, other.NameAndBirthdate)) return false;
      if (VersionNumber != other.VersionNumber) return false;
      if (DeviceId != other.DeviceId) return false;
      if (ClientId != other.ClientId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (nameAndBirthdate_ != null) hash ^= NameAndBirthdate.GetHashCode();
      if (VersionNumber != 0) hash ^= VersionNumber.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nameAndBirthdate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NameAndBirthdate);
      }
      if (VersionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DeviceId);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClientId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nameAndBirthdate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NameAndBirthdate);
      }
      if (VersionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DeviceId);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ClientId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (nameAndBirthdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NameAndBirthdate);
      }
      if (VersionNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SCSuggestUsernamePbSuggestUsernameRequestV2 other) {
      if (other == null) {
        return;
      }
      if (other.nameAndBirthdate_ != null) {
        if (nameAndBirthdate_ == null) {
          NameAndBirthdate = new global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate();
        }
        NameAndBirthdate.MergeFrom(other.NameAndBirthdate);
      }
      if (other.VersionNumber != 0) {
        VersionNumber = other.VersionNumber;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (nameAndBirthdate_ == null) {
              NameAndBirthdate = new global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate();
            }
            input.ReadMessage(NameAndBirthdate);
            break;
          }
          case 16: {
            VersionNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            DeviceId = input.ReadString();
            break;
          }
          case 34: {
            ClientId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (nameAndBirthdate_ == null) {
              NameAndBirthdate = new global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Types.NameAndBirthdate();
            }
            input.ReadMessage(NameAndBirthdate);
            break;
          }
          case 16: {
            VersionNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            DeviceId = input.ReadString();
            break;
          }
          case 34: {
            ClientId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SCSuggestUsernamePbSuggestUsernameRequestV2 message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class NameAndBirthdate : pb::IMessage<NameAndBirthdate>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<NameAndBirthdate> _parser = new pb::MessageParser<NameAndBirthdate>(() => new NameAndBirthdate());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<NameAndBirthdate> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbSuggestUsernameRequestV2.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NameAndBirthdate() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NameAndBirthdate(NameAndBirthdate other) : this() {
          firstName_ = other.firstName_;
          lastName_ = other.lastName_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public NameAndBirthdate Clone() {
          return new NameAndBirthdate(this);
        }

        /// <summary>Field number for the "firstName" field.</summary>
        public const int FirstNameFieldNumber = 1;
        private string firstName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string FirstName {
          get { return firstName_; }
          set {
            firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "lastName" field.</summary>
        public const int LastNameFieldNumber = 2;
        private string lastName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string LastName {
          get { return lastName_; }
          set {
            lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as NameAndBirthdate);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(NameAndBirthdate other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (FirstName != other.FirstName) return false;
          if (LastName != other.LastName) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
          if (LastName.Length != 0) hash ^= LastName.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (FirstName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(FirstName);
          }
          if (LastName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(LastName);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (FirstName.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(FirstName);
          }
          if (LastName.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(LastName);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (FirstName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
          }
          if (LastName.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(NameAndBirthdate other) {
          if (other == null) {
            return;
          }
          if (other.FirstName.Length != 0) {
            FirstName = other.FirstName;
          }
          if (other.LastName.Length != 0) {
            LastName = other.LastName;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                FirstName = input.ReadString();
                break;
              }
              case 18: {
                LastName = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                FirstName = input.ReadString();
                break;
              }
              case 18: {
                LastName = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// Define the response message for username suggestion
  /// </summary>
  public sealed partial class SCSuggestUsernamePbSuggestUsernameResponseV2 : pb::IMessage<SCSuggestUsernamePbSuggestUsernameResponseV2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SCSuggestUsernamePbSuggestUsernameResponseV2> _parser = new pb::MessageParser<SCSuggestUsernamePbSuggestUsernameResponseV2>(() => new SCSuggestUsernamePbSuggestUsernameResponseV2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SCSuggestUsernamePbSuggestUsernameResponseV2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.SuggestUsernameServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameResponseV2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameResponseV2(SCSuggestUsernamePbSuggestUsernameResponseV2 other) : this() {
      suggestionsArray_ = other.suggestionsArray_.Clone();
      versionNumber_ = other.versionNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbSuggestUsernameResponseV2 Clone() {
      return new SCSuggestUsernamePbSuggestUsernameResponseV2(this);
    }

    /// <summary>Field number for the "suggestionsArray" field.</summary>
    public const int SuggestionsArrayFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_suggestionsArray_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> suggestionsArray_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> SuggestionsArray {
      get { return suggestionsArray_; }
    }

    /// <summary>Field number for the "versionNumber" field.</summary>
    public const int VersionNumberFieldNumber = 2;
    private uint versionNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint VersionNumber {
      get { return versionNumber_; }
      set {
        versionNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SCSuggestUsernamePbSuggestUsernameResponseV2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SCSuggestUsernamePbSuggestUsernameResponseV2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!suggestionsArray_.Equals(other.suggestionsArray_)) return false;
      if (VersionNumber != other.VersionNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= suggestionsArray_.GetHashCode();
      if (VersionNumber != 0) hash ^= VersionNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      suggestionsArray_.WriteTo(output, _repeated_suggestionsArray_codec);
      if (VersionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VersionNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      suggestionsArray_.WriteTo(ref output, _repeated_suggestionsArray_codec);
      if (VersionNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(VersionNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += suggestionsArray_.CalculateSize(_repeated_suggestionsArray_codec);
      if (VersionNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VersionNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SCSuggestUsernamePbSuggestUsernameResponseV2 other) {
      if (other == null) {
        return;
      }
      suggestionsArray_.Add(other.suggestionsArray_);
      if (other.VersionNumber != 0) {
        VersionNumber = other.VersionNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            suggestionsArray_.AddEntriesFrom(input, _repeated_suggestionsArray_codec);
            break;
          }
          case 16: {
            VersionNumber = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            suggestionsArray_.AddEntriesFrom(ref input, _repeated_suggestionsArray_codec);
            break;
          }
          case 16: {
            VersionNumber = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Define the request message for checking username availability
  /// </summary>
  public sealed partial class SCSuggestUsernamePbCheckUsernameRequestV2 : pb::IMessage<SCSuggestUsernamePbCheckUsernameRequestV2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SCSuggestUsernamePbCheckUsernameRequestV2> _parser = new pb::MessageParser<SCSuggestUsernamePbCheckUsernameRequestV2>(() => new SCSuggestUsernamePbCheckUsernameRequestV2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SCSuggestUsernamePbCheckUsernameRequestV2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.SuggestUsernameServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameRequestV2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameRequestV2(SCSuggestUsernamePbCheckUsernameRequestV2 other) : this() {
      requestedUsername_ = other.requestedUsername_;
      versionNumber_ = other.versionNumber_;
      deviceId_ = other.deviceId_;
      clientId_ = other.clientId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameRequestV2 Clone() {
      return new SCSuggestUsernamePbCheckUsernameRequestV2(this);
    }

    /// <summary>Field number for the "requestedUsername" field.</summary>
    public const int RequestedUsernameFieldNumber = 1;
    private string requestedUsername_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestedUsername {
      get { return requestedUsername_; }
      set {
        requestedUsername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "versionNumber" field.</summary>
    public const int VersionNumberFieldNumber = 3;
    private uint versionNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint VersionNumber {
      get { return versionNumber_; }
      set {
        versionNumber_ = value;
      }
    }

    /// <summary>Field number for the "deviceId" field.</summary>
    public const int DeviceIdFieldNumber = 4;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clientId" field.</summary>
    public const int ClientIdFieldNumber = 5;
    private string clientId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SCSuggestUsernamePbCheckUsernameRequestV2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SCSuggestUsernamePbCheckUsernameRequestV2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestedUsername != other.RequestedUsername) return false;
      if (VersionNumber != other.VersionNumber) return false;
      if (DeviceId != other.DeviceId) return false;
      if (ClientId != other.ClientId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestedUsername.Length != 0) hash ^= RequestedUsername.GetHashCode();
      if (VersionNumber != 0) hash ^= VersionNumber.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestedUsername.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestedUsername);
      }
      if (VersionNumber != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DeviceId);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestedUsername.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestedUsername);
      }
      if (VersionNumber != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DeviceId);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestedUsername.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestedUsername);
      }
      if (VersionNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VersionNumber);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SCSuggestUsernamePbCheckUsernameRequestV2 other) {
      if (other == null) {
        return;
      }
      if (other.RequestedUsername.Length != 0) {
        RequestedUsername = other.RequestedUsername;
      }
      if (other.VersionNumber != 0) {
        VersionNumber = other.VersionNumber;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestedUsername = input.ReadString();
            break;
          }
          case 24: {
            VersionNumber = input.ReadUInt32();
            break;
          }
          case 34: {
            DeviceId = input.ReadString();
            break;
          }
          case 42: {
            ClientId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RequestedUsername = input.ReadString();
            break;
          }
          case 24: {
            VersionNumber = input.ReadUInt32();
            break;
          }
          case 34: {
            DeviceId = input.ReadString();
            break;
          }
          case 42: {
            ClientId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SCSuggestUsernamePbCheckUsernameResponseV2 : pb::IMessage<SCSuggestUsernamePbCheckUsernameResponseV2>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SCSuggestUsernamePbCheckUsernameResponseV2> _parser = new pb::MessageParser<SCSuggestUsernamePbCheckUsernameResponseV2>(() => new SCSuggestUsernamePbCheckUsernameResponseV2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SCSuggestUsernamePbCheckUsernameResponseV2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SnapchatLibProto.Snapchat.Activation.Api.SuggestUsernameServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameResponseV2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameResponseV2(SCSuggestUsernamePbCheckUsernameResponseV2 other) : this() {
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SCSuggestUsernamePbCheckUsernameResponseV2 Clone() {
      return new SCSuggestUsernamePbCheckUsernameResponseV2(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState state_ = global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SCSuggestUsernamePbCheckUsernameResponseV2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SCSuggestUsernamePbCheckUsernameResponseV2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (State != global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (State != global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (State != global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (State != global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SCSuggestUsernamePbCheckUsernameResponseV2 other) {
      if (other == null) {
        return;
      }
      if (other.State != global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState.StateUnset) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            State = (global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            State = (global::SnapchatLibProto.Snapchat.Activation.Api.SCSuggestUsernamePbCheckUsernameResponseV2.Types.SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SCSuggestUsernamePbCheckUsernameResponseV2 message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState {
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_StateUnset")] StateUnset = 0,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_UsernameAvailable")] UsernameAvailable = 1,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_TooShort")] TooShort = 2,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_TooLong")] TooLong = 3,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_InvalidBegin")] InvalidBegin = 4,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_InvalidEnd")] InvalidEnd = 5,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_InvalidChar")] InvalidChar = 6,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_InvalidSeparated")] InvalidSeparated = 7,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_Taken")] Taken = 8,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_Deleted")] Deleted = 9,
        [pbr::OriginalName("SCSuggestUsernamePbCheckUsernameResponse_RequestedUsernameState_SameAsPassword")] SameAsPassword = 10,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
