// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VendorAttestation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from VendorAttestation.proto</summary>
public static partial class VendorAttestationReflection {

  #region Descriptor
  /// <summary>File descriptor for VendorAttestation.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static VendorAttestationReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdWZW5kb3JBdHRlc3RhdGlvbi5wcm90byL6CgoRVmVuZG9yQXR0ZXN0YXRp",
          "b24SOAoEdHlwZRgBIAEoDjIqLlZlbmRvckF0dGVzdGF0aW9uLlZlbmRvckF0",
          "dGVzdGF0aW9uTGliYXJ5Eg8KB3BheWxvYWQYAiABKAwSJwoac3RyaWN0RW5m",
          "b3JjZW1lbnRzUmVxdWlyZWQYAyABKAhIAIgBARINCgVlcnJvchgEIAEoCRIa",
          "ChJhbmRyb2lkUGFja2FnZU5hbWUYBSABKAkSHgoRc3RhbmRhcmRFcnJvckNv",
          "ZGUYBiABKAVIAYgBARJFChRhcHBBdHRlc3RFbmZvcmNlbWVudBgHIAEoDjIn",
          "LlZlbmRvckF0dGVzdGF0aW9uLkFwcEF0dGVzdEVuZm9yY2VtZW50EhYKDmFw",
          "cEF0dGVzdEtleUlkGAggASgJEhYKDmFwcEF0dGVzdE5vbmNlGAkgASgJEhoK",
          "EmFwcEF0dGVzdEFzc2VydGlvbhgKIAEoDBIdChVrZXlBdHRlc3RhdG9uS2V5",
          "QWxpYXMYCyABKAkSHQoVa2V5QXR0ZXN0YXRvbktleU5vbmNlGAwgASgMEiQK",
          "HGtleUF0dGVzdGF0aW9uQ2VydENoYWluQXJyYXkYDSADKAwSGwoTa2V5QXR0",
          "ZXN0YXRpb25FcnJvchgOIAEoCRInCh9rZXlBdHRlc3RhdGlvblN0YW5kYXJk",
          "RXJyb3JDb2RlGA8gASgFIvkBChRBcHBBdHRlc3RFbmZvcmNlbWVudBJDCj9B",
          "cHBBdHRlc3RFbmZvcmNlbWVudF9BcHBBdHRlc3RFbmZvcmNlbWVudF9BcHBB",
          "dHRlc3REZWZhdWx0VW5zZXQQABJJCkVBcHBBdHRlc3RFbmZvcmNlbWVudF9B",
          "cHBBdHRlc3RFbmZvcmNlbWVudF9BcHBBdHRlc3RLZXlBdHRlc3RhdGlvbk9u",
          "bHkQARJRCk1BcHBBdHRlc3RFbmZvcmNlbWVudF9BcHBBdHRlc3RFbmZvcmNl",
          "bWVudF9BcHBBdHRlc3RLZXlBdHRlc3RhdGlvbkFuZEFzc2VydGlvbhACIrcE",
          "ChdWZW5kb3JBdHRlc3RhdGlvbkxpYmFyeRI/CjtWZW5kb3JBdHRlc3RhdGlv",
          "bkxpYmFyeV9WZW5kb3JBdHRlc3RhdGlvbkxpYmFyeVVua25vd25VbnNldBAA",
          "EjwKOFZlbmRvckF0dGVzdGF0aW9uTGliYXJ5X1ZlbmRvckF0dGVzdGF0aW9u",
          "TGliYXJ5U2FmZXR5TmV0EAESQAo8VmVuZG9yQXR0ZXN0YXRpb25MaWJhcnlf",
          "VmVuZG9yQXR0ZXN0YXRpb25MaWJhcnlQbGF5SW50ZWdyaXR5EAISPwo7VmVu",
          "ZG9yQXR0ZXN0YXRpb25MaWJhcnlfVmVuZG9yQXR0ZXN0YXRpb25MaWJhcnlT",
          "eXNJbnRlZ3JpdHkQAxI8CjhWZW5kb3JBdHRlc3RhdGlvbkxpYmFyeV9WZW5k",
          "b3JBdHRlc3RhdGlvbkxpYmFyeUFwcEF0dGVzdBAEEkEKPVZlbmRvckF0dGVz",
          "dGF0aW9uTGliYXJ5X1ZlbmRvckF0dGVzdGF0aW9uTGliYXJ5S2V5QXR0ZXN0",
          "YXRpb24QBRJOCkpWZW5kb3JBdHRlc3RhdGlvbkxpYmFyeV9WZW5kb3JBdHRl",
          "c3RhdGlvbkxpYmFyeVBsYXlJbnRlZ3JpdHlBbmRBdHRlc3RhdGlvbhAGEkkK",
          "RVZlbmRvckF0dGVzdGF0aW9uTGliYXJ5X1ZlbmRvckF0dGVzdGF0aW9uTGli",
          "YXJ5U2FmZXR5TmVBbmRBdHRlc3RhdGlvbhAHQh0KG19zdHJpY3RFbmZvcmNl",
          "bWVudHNSZXF1aXJlZEIUChJfc3RhbmRhcmRFcnJvckNvZGViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::VendorAttestation), global::VendorAttestation.Parser, new[]{ "Type", "Payload", "StrictEnforcementsRequired", "Error", "AndroidPackageName", "StandardErrorCode", "AppAttestEnforcement", "AppAttestKeyId", "AppAttestNonce", "AppAttestAssertion", "KeyAttestatonKeyAlias", "KeyAttestatonKeyNonce", "KeyAttestationCertChainArray", "KeyAttestationError", "KeyAttestationStandardErrorCode" }, new[]{ "StrictEnforcementsRequired", "StandardErrorCode" }, new[]{ typeof(global::VendorAttestation.Types.AppAttestEnforcement), typeof(global::VendorAttestation.Types.VendorAttestationLibary) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class VendorAttestation : pb::IMessage<VendorAttestation>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<VendorAttestation> _parser = new pb::MessageParser<VendorAttestation>(() => new VendorAttestation());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<VendorAttestation> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::VendorAttestationReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public VendorAttestation() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public VendorAttestation(VendorAttestation other) : this() {
    _hasBits0 = other._hasBits0;
    type_ = other.type_;
    payload_ = other.payload_;
    strictEnforcementsRequired_ = other.strictEnforcementsRequired_;
    error_ = other.error_;
    androidPackageName_ = other.androidPackageName_;
    standardErrorCode_ = other.standardErrorCode_;
    appAttestEnforcement_ = other.appAttestEnforcement_;
    appAttestKeyId_ = other.appAttestKeyId_;
    appAttestNonce_ = other.appAttestNonce_;
    appAttestAssertion_ = other.appAttestAssertion_;
    keyAttestatonKeyAlias_ = other.keyAttestatonKeyAlias_;
    keyAttestatonKeyNonce_ = other.keyAttestatonKeyNonce_;
    keyAttestationCertChainArray_ = other.keyAttestationCertChainArray_.Clone();
    keyAttestationError_ = other.keyAttestationError_;
    keyAttestationStandardErrorCode_ = other.keyAttestationStandardErrorCode_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public VendorAttestation Clone() {
    return new VendorAttestation(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::VendorAttestation.Types.VendorAttestationLibary type_ = global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::VendorAttestation.Types.VendorAttestationLibary Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 2;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "strictEnforcementsRequired" field.</summary>
  public const int StrictEnforcementsRequiredFieldNumber = 3;
  private readonly static bool StrictEnforcementsRequiredDefaultValue = false;

  private bool strictEnforcementsRequired_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool StrictEnforcementsRequired {
    get { if ((_hasBits0 & 1) != 0) { return strictEnforcementsRequired_; } else { return StrictEnforcementsRequiredDefaultValue; } }
    set {
      _hasBits0 |= 1;
      strictEnforcementsRequired_ = value;
    }
  }
  /// <summary>Gets whether the "strictEnforcementsRequired" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasStrictEnforcementsRequired {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "strictEnforcementsRequired" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearStrictEnforcementsRequired() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 4;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "androidPackageName" field.</summary>
  public const int AndroidPackageNameFieldNumber = 5;
  private string androidPackageName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AndroidPackageName {
    get { return androidPackageName_; }
    set {
      androidPackageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "standardErrorCode" field.</summary>
  public const int StandardErrorCodeFieldNumber = 6;
  private readonly static int StandardErrorCodeDefaultValue = 0;

  private int standardErrorCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int StandardErrorCode {
    get { if ((_hasBits0 & 2) != 0) { return standardErrorCode_; } else { return StandardErrorCodeDefaultValue; } }
    set {
      _hasBits0 |= 2;
      standardErrorCode_ = value;
    }
  }
  /// <summary>Gets whether the "standardErrorCode" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasStandardErrorCode {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "standardErrorCode" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearStandardErrorCode() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "appAttestEnforcement" field.</summary>
  public const int AppAttestEnforcementFieldNumber = 7;
  private global::VendorAttestation.Types.AppAttestEnforcement appAttestEnforcement_ = global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::VendorAttestation.Types.AppAttestEnforcement AppAttestEnforcement {
    get { return appAttestEnforcement_; }
    set {
      appAttestEnforcement_ = value;
    }
  }

  /// <summary>Field number for the "appAttestKeyId" field.</summary>
  public const int AppAttestKeyIdFieldNumber = 8;
  private string appAttestKeyId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppAttestKeyId {
    get { return appAttestKeyId_; }
    set {
      appAttestKeyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "appAttestNonce" field.</summary>
  public const int AppAttestNonceFieldNumber = 9;
  private string appAttestNonce_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppAttestNonce {
    get { return appAttestNonce_; }
    set {
      appAttestNonce_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "appAttestAssertion" field.</summary>
  public const int AppAttestAssertionFieldNumber = 10;
  private pb::ByteString appAttestAssertion_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString AppAttestAssertion {
    get { return appAttestAssertion_; }
    set {
      appAttestAssertion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "keyAttestatonKeyAlias" field.</summary>
  public const int KeyAttestatonKeyAliasFieldNumber = 11;
  private string keyAttestatonKeyAlias_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string KeyAttestatonKeyAlias {
    get { return keyAttestatonKeyAlias_; }
    set {
      keyAttestatonKeyAlias_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "keyAttestatonKeyNonce" field.</summary>
  public const int KeyAttestatonKeyNonceFieldNumber = 12;
  private pb::ByteString keyAttestatonKeyNonce_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString KeyAttestatonKeyNonce {
    get { return keyAttestatonKeyNonce_; }
    set {
      keyAttestatonKeyNonce_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "keyAttestationCertChainArray" field.</summary>
  public const int KeyAttestationCertChainArrayFieldNumber = 13;
  private static readonly pb::FieldCodec<pb::ByteString> _repeated_keyAttestationCertChainArray_codec
      = pb::FieldCodec.ForBytes(106);
  private readonly pbc::RepeatedField<pb::ByteString> keyAttestationCertChainArray_ = new pbc::RepeatedField<pb::ByteString>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<pb::ByteString> KeyAttestationCertChainArray {
    get { return keyAttestationCertChainArray_; }
  }

  /// <summary>Field number for the "keyAttestationError" field.</summary>
  public const int KeyAttestationErrorFieldNumber = 14;
  private string keyAttestationError_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string KeyAttestationError {
    get { return keyAttestationError_; }
    set {
      keyAttestationError_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "keyAttestationStandardErrorCode" field.</summary>
  public const int KeyAttestationStandardErrorCodeFieldNumber = 15;
  private int keyAttestationStandardErrorCode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int KeyAttestationStandardErrorCode {
    get { return keyAttestationStandardErrorCode_; }
    set {
      keyAttestationStandardErrorCode_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as VendorAttestation);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(VendorAttestation other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Payload != other.Payload) return false;
    if (StrictEnforcementsRequired != other.StrictEnforcementsRequired) return false;
    if (Error != other.Error) return false;
    if (AndroidPackageName != other.AndroidPackageName) return false;
    if (StandardErrorCode != other.StandardErrorCode) return false;
    if (AppAttestEnforcement != other.AppAttestEnforcement) return false;
    if (AppAttestKeyId != other.AppAttestKeyId) return false;
    if (AppAttestNonce != other.AppAttestNonce) return false;
    if (AppAttestAssertion != other.AppAttestAssertion) return false;
    if (KeyAttestatonKeyAlias != other.KeyAttestatonKeyAlias) return false;
    if (KeyAttestatonKeyNonce != other.KeyAttestatonKeyNonce) return false;
    if(!keyAttestationCertChainArray_.Equals(other.keyAttestationCertChainArray_)) return false;
    if (KeyAttestationError != other.KeyAttestationError) return false;
    if (KeyAttestationStandardErrorCode != other.KeyAttestationStandardErrorCode) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset) hash ^= Type.GetHashCode();
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (HasStrictEnforcementsRequired) hash ^= StrictEnforcementsRequired.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (AndroidPackageName.Length != 0) hash ^= AndroidPackageName.GetHashCode();
    if (HasStandardErrorCode) hash ^= StandardErrorCode.GetHashCode();
    if (AppAttestEnforcement != global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset) hash ^= AppAttestEnforcement.GetHashCode();
    if (AppAttestKeyId.Length != 0) hash ^= AppAttestKeyId.GetHashCode();
    if (AppAttestNonce.Length != 0) hash ^= AppAttestNonce.GetHashCode();
    if (AppAttestAssertion.Length != 0) hash ^= AppAttestAssertion.GetHashCode();
    if (KeyAttestatonKeyAlias.Length != 0) hash ^= KeyAttestatonKeyAlias.GetHashCode();
    if (KeyAttestatonKeyNonce.Length != 0) hash ^= KeyAttestatonKeyNonce.GetHashCode();
    hash ^= keyAttestationCertChainArray_.GetHashCode();
    if (KeyAttestationError.Length != 0) hash ^= KeyAttestationError.GetHashCode();
    if (KeyAttestationStandardErrorCode != 0) hash ^= KeyAttestationStandardErrorCode.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (HasStrictEnforcementsRequired) {
      output.WriteRawTag(24);
      output.WriteBool(StrictEnforcementsRequired);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Error);
    }
    if (AndroidPackageName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AndroidPackageName);
    }
    if (HasStandardErrorCode) {
      output.WriteRawTag(48);
      output.WriteInt32(StandardErrorCode);
    }
    if (AppAttestEnforcement != global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset) {
      output.WriteRawTag(56);
      output.WriteEnum((int) AppAttestEnforcement);
    }
    if (AppAttestKeyId.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(AppAttestKeyId);
    }
    if (AppAttestNonce.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(AppAttestNonce);
    }
    if (AppAttestAssertion.Length != 0) {
      output.WriteRawTag(82);
      output.WriteBytes(AppAttestAssertion);
    }
    if (KeyAttestatonKeyAlias.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(KeyAttestatonKeyAlias);
    }
    if (KeyAttestatonKeyNonce.Length != 0) {
      output.WriteRawTag(98);
      output.WriteBytes(KeyAttestatonKeyNonce);
    }
    keyAttestationCertChainArray_.WriteTo(output, _repeated_keyAttestationCertChainArray_codec);
    if (KeyAttestationError.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(KeyAttestationError);
    }
    if (KeyAttestationStandardErrorCode != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(KeyAttestationStandardErrorCode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(Payload);
    }
    if (HasStrictEnforcementsRequired) {
      output.WriteRawTag(24);
      output.WriteBool(StrictEnforcementsRequired);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Error);
    }
    if (AndroidPackageName.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AndroidPackageName);
    }
    if (HasStandardErrorCode) {
      output.WriteRawTag(48);
      output.WriteInt32(StandardErrorCode);
    }
    if (AppAttestEnforcement != global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset) {
      output.WriteRawTag(56);
      output.WriteEnum((int) AppAttestEnforcement);
    }
    if (AppAttestKeyId.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(AppAttestKeyId);
    }
    if (AppAttestNonce.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(AppAttestNonce);
    }
    if (AppAttestAssertion.Length != 0) {
      output.WriteRawTag(82);
      output.WriteBytes(AppAttestAssertion);
    }
    if (KeyAttestatonKeyAlias.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(KeyAttestatonKeyAlias);
    }
    if (KeyAttestatonKeyNonce.Length != 0) {
      output.WriteRawTag(98);
      output.WriteBytes(KeyAttestatonKeyNonce);
    }
    keyAttestationCertChainArray_.WriteTo(ref output, _repeated_keyAttestationCertChainArray_codec);
    if (KeyAttestationError.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(KeyAttestationError);
    }
    if (KeyAttestationStandardErrorCode != 0) {
      output.WriteRawTag(120);
      output.WriteInt32(KeyAttestationStandardErrorCode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (HasStrictEnforcementsRequired) {
      size += 1 + 1;
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    if (AndroidPackageName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AndroidPackageName);
    }
    if (HasStandardErrorCode) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(StandardErrorCode);
    }
    if (AppAttestEnforcement != global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AppAttestEnforcement);
    }
    if (AppAttestKeyId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppAttestKeyId);
    }
    if (AppAttestNonce.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppAttestNonce);
    }
    if (AppAttestAssertion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(AppAttestAssertion);
    }
    if (KeyAttestatonKeyAlias.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyAttestatonKeyAlias);
    }
    if (KeyAttestatonKeyNonce.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(KeyAttestatonKeyNonce);
    }
    size += keyAttestationCertChainArray_.CalculateSize(_repeated_keyAttestationCertChainArray_codec);
    if (KeyAttestationError.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(KeyAttestationError);
    }
    if (KeyAttestationStandardErrorCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(KeyAttestationStandardErrorCode);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(VendorAttestation other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::VendorAttestation.Types.VendorAttestationLibary.VendorAttestationLibaryUnknownUnset) {
      Type = other.Type;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    if (other.HasStrictEnforcementsRequired) {
      StrictEnforcementsRequired = other.StrictEnforcementsRequired;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    if (other.AndroidPackageName.Length != 0) {
      AndroidPackageName = other.AndroidPackageName;
    }
    if (other.HasStandardErrorCode) {
      StandardErrorCode = other.StandardErrorCode;
    }
    if (other.AppAttestEnforcement != global::VendorAttestation.Types.AppAttestEnforcement.AppAttestEnforcementAppAttestDefaultUnset) {
      AppAttestEnforcement = other.AppAttestEnforcement;
    }
    if (other.AppAttestKeyId.Length != 0) {
      AppAttestKeyId = other.AppAttestKeyId;
    }
    if (other.AppAttestNonce.Length != 0) {
      AppAttestNonce = other.AppAttestNonce;
    }
    if (other.AppAttestAssertion.Length != 0) {
      AppAttestAssertion = other.AppAttestAssertion;
    }
    if (other.KeyAttestatonKeyAlias.Length != 0) {
      KeyAttestatonKeyAlias = other.KeyAttestatonKeyAlias;
    }
    if (other.KeyAttestatonKeyNonce.Length != 0) {
      KeyAttestatonKeyNonce = other.KeyAttestatonKeyNonce;
    }
    keyAttestationCertChainArray_.Add(other.keyAttestationCertChainArray_);
    if (other.KeyAttestationError.Length != 0) {
      KeyAttestationError = other.KeyAttestationError;
    }
    if (other.KeyAttestationStandardErrorCode != 0) {
      KeyAttestationStandardErrorCode = other.KeyAttestationStandardErrorCode;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::VendorAttestation.Types.VendorAttestationLibary) input.ReadEnum();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 24: {
          StrictEnforcementsRequired = input.ReadBool();
          break;
        }
        case 34: {
          Error = input.ReadString();
          break;
        }
        case 42: {
          AndroidPackageName = input.ReadString();
          break;
        }
        case 48: {
          StandardErrorCode = input.ReadInt32();
          break;
        }
        case 56: {
          AppAttestEnforcement = (global::VendorAttestation.Types.AppAttestEnforcement) input.ReadEnum();
          break;
        }
        case 66: {
          AppAttestKeyId = input.ReadString();
          break;
        }
        case 74: {
          AppAttestNonce = input.ReadString();
          break;
        }
        case 82: {
          AppAttestAssertion = input.ReadBytes();
          break;
        }
        case 90: {
          KeyAttestatonKeyAlias = input.ReadString();
          break;
        }
        case 98: {
          KeyAttestatonKeyNonce = input.ReadBytes();
          break;
        }
        case 106: {
          keyAttestationCertChainArray_.AddEntriesFrom(input, _repeated_keyAttestationCertChainArray_codec);
          break;
        }
        case 114: {
          KeyAttestationError = input.ReadString();
          break;
        }
        case 120: {
          KeyAttestationStandardErrorCode = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::VendorAttestation.Types.VendorAttestationLibary) input.ReadEnum();
          break;
        }
        case 18: {
          Payload = input.ReadBytes();
          break;
        }
        case 24: {
          StrictEnforcementsRequired = input.ReadBool();
          break;
        }
        case 34: {
          Error = input.ReadString();
          break;
        }
        case 42: {
          AndroidPackageName = input.ReadString();
          break;
        }
        case 48: {
          StandardErrorCode = input.ReadInt32();
          break;
        }
        case 56: {
          AppAttestEnforcement = (global::VendorAttestation.Types.AppAttestEnforcement) input.ReadEnum();
          break;
        }
        case 66: {
          AppAttestKeyId = input.ReadString();
          break;
        }
        case 74: {
          AppAttestNonce = input.ReadString();
          break;
        }
        case 82: {
          AppAttestAssertion = input.ReadBytes();
          break;
        }
        case 90: {
          KeyAttestatonKeyAlias = input.ReadString();
          break;
        }
        case 98: {
          KeyAttestatonKeyNonce = input.ReadBytes();
          break;
        }
        case 106: {
          keyAttestationCertChainArray_.AddEntriesFrom(ref input, _repeated_keyAttestationCertChainArray_codec);
          break;
        }
        case 114: {
          KeyAttestationError = input.ReadString();
          break;
        }
        case 120: {
          KeyAttestationStandardErrorCode = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the VendorAttestation message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum AppAttestEnforcement {
      [pbr::OriginalName("AppAttestEnforcement_AppAttestEnforcement_AppAttestDefaultUnset")] AppAttestEnforcementAppAttestDefaultUnset = 0,
      [pbr::OriginalName("AppAttestEnforcement_AppAttestEnforcement_AppAttestKeyAttestationOnly")] AppAttestEnforcementAppAttestKeyAttestationOnly = 1,
      [pbr::OriginalName("AppAttestEnforcement_AppAttestEnforcement_AppAttestKeyAttestationAndAssertion")] AppAttestEnforcementAppAttestKeyAttestationAndAssertion = 2,
    }

    public enum VendorAttestationLibary {
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibaryUnknownUnset")] VendorAttestationLibaryUnknownUnset = 0,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibarySafetyNet")] VendorAttestationLibarySafetyNet = 1,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibaryPlayIntegrity")] VendorAttestationLibaryPlayIntegrity = 2,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibarySysIntegrity")] VendorAttestationLibarySysIntegrity = 3,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibaryAppAttest")] VendorAttestationLibaryAppAttest = 4,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibaryKeyAttestation")] VendorAttestationLibaryKeyAttestation = 5,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibaryPlayIntegrityAndAttestation")] VendorAttestationLibaryPlayIntegrityAndAttestation = 6,
      [pbr::OriginalName("VendorAttestationLibary_VendorAttestationLibarySafetyNeAndAttestation")] VendorAttestationLibarySafetyNeAndAttestation = 7,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
